(async function(){
const G=await GameAPI.loadGames(),C=GAME_CATEGORIES,res=document.getElementById("results"),q=document.getElementById("search");
const T=[["0-5","0~5시간"],["6-10","6~10시간"],["11-15","11~15시간"],["16-20","16~20시간"],["21-25","21~25시간"],["26-30","26~30시간"],["31-35","31~35시간"],["36-40","36~40시간"],["41-45","41~45시간"],["46-50","46~50시간"],["50+","50시간+"],["storyless","스토리 없음"]];
let tags=new Set(),times=new Set();
function img(g){let a=steamImage(g.steamApp),b=steamImageFallback(g.steamApp);return `<img src="${a}" loading="lazy" alt="${g.name}" referrerpolicy="no-referrer" onerror="if(!this.dataset.f){this.dataset.f=1;this.src='${b}'}else{this.style.display='none';this.nextElementSibling.style.display='flex'}"><div class="image-fallback">${g.name}</div>`}
function sync(){let p=new URLSearchParams;tags.forEach(x=>p.append("tag",x));times.forEach(x=>p.append("time",x));if(q.value.trim())p.set("q",q.value.trim());history.replaceState(null,"","category.html"+(p.toString()?"?"+p:""))}
function states(){document.querySelectorAll(".filter-chip").forEach(b=>b.classList.toggle("active",tags.has(b.dataset.tag)));document.querySelectorAll(".time-chip").forEach(b=>b.classList.toggle("active",times.has(b.dataset.time)))}
function render(){let s=q.value.trim().toLowerCase(),arr=G.filter(g=>(!tags.size||[...tags].every(t=>(g.tags||[]).includes(t)))&&(!times.size||times.has(timeBucket(g)))&&(!s||(g.name+" "+(g.desc||'')+" "+(g.tags||[]).join(" ")).toLowerCase().includes(s)));res.innerHTML="";if(!arr.length)res.innerHTML='<div class="empty">선택한 조건에 맞는 게임이 없습니다.</div>';arr.forEach(g=>{let c=document.createElement("article");c.className="game-card";c.innerHTML=`<div class="game-cover">${img(g)}</div><div class="game-info"><div class="game-title-row"><div class="game-title">${g.name}</div><div class="game-time">${timeText(g)}</div></div><div class="game-desc">${g.desc||''}</div><div class="tags">${(g.tags||[]).slice(0,5).map(t=>`<button class="tag" data-tag="${t}">${t}</button>`).join("")}</div></div>`;c.onclick=e=>{let b=e.target.closest(".tag");if(b){e.stopPropagation();tags.add(b.dataset.tag);states();render();sync();window.scrollTo({top:0,behavior:"smooth"})}else location.href="game-detail.html?game="+encodeURIComponent(g.id)};res.appendChild(c)});let a=[];if(tags.size)a.push([...tags].join(", "));if(times.size)a.push([...times].map(x=>T.find(y=>y[0]===x)?.[1]).join(", "));if(s)a.push('"'+q.value.trim()+'"');document.getElementById("resultTitle").textContent=a.length?a.join(" · "):"전체 게임";document.getElementById("count").textContent=arr.length+"개"}
C.forEach(x=>{let b=document.createElement("button");b.className="filter-chip";b.dataset.tag=x;b.textContent=x;b.onclick=()=>{tags.has(x)?tags.delete(x):tags.add(x);states();render();sync()};document.getElementById("cats").appendChild(b)});
T.forEach(([v,l])=>{let b=document.createElement("button");b.className="time-chip";b.dataset.time=v;b.textContent=l;b.onclick=()=>{times.has(v)?times.delete(v):times.add(v);states();render();sync()};document.getElementById("times").appendChild(b)});
let p=new URLSearchParams(location.search);p.getAll("tag").forEach(x=>{if(C.includes(x))tags.add(x)});p.getAll("time").forEach(x=>{if(T.some(y=>y[0]===x))times.add(x)});q.value=p.get("q")||"";states();render();
q.oninput=()=>{render();sync()};document.getElementById("clearQ").onclick=()=>{q.value="";render();sync()};document.getElementById("reset").onclick=()=>{tags.clear();times.clear();q.value="";states();render();sync()};
})();
