(async function(){
const G=await GameAPI.loadGames(),grid=document.getElementById("popularGrid"),chips=[...document.querySelectorAll(".chip")];
function img(g){let a=steamImage(g.steamApp),b=steamImageFallback(g.steamApp);return `<img src="${a}" alt="${g.name} Steam 이미지" referrerpolicy="no-referrer" onerror="if(!this.dataset.f){this.dataset.f=1;this.src='${b}'}else{this.style.display='none';this.nextElementSibling.style.display='flex'}"><div class="image-fallback">${g.name}</div>`}
G.slice(0,5).forEach(g=>{let c=document.createElement("article");c.className="game-card";c.innerHTML=`<div class="game-cover">${img(g)}</div><div class="game-info"><div class="game-title-row"><div class="game-title">${g.name}</div><div class="game-time">Steam ${Number(g.steamRating||0).toFixed(1)}%</div></div><div class="game-desc">${g.desc||''}</div><div class="tags">${(g.tags||[]).slice(0,3).map(t=>`<a class="tag" href="category.html?tag=${encodeURIComponent(t)}">${t}</a>`).join("")}</div></div>`;c.onclick=e=>{if(!e.target.closest(".tag"))location.href="game-detail.html?game="+encodeURIComponent(g.id)};grid.appendChild(c)});
chips.forEach(b=>b.onclick=()=>b.classList.toggle("active"));
document.getElementById("recommend").onclick=()=>{let s=chips.filter(x=>x.classList.contains("active")).map(x=>x.dataset.tag),p=G.filter(g=>s.every(t=>(g.tags||[]).includes(t)));if(!p.length)p=G;let g=p[Math.floor(Math.random()*p.length)];document.getElementById("rouletteResult").textContent="✨ 추천: "+g.name};
document.getElementById("spin").onclick=()=>{let w=document.getElementById("wheel");if(w.classList.contains("spin"))return;w.classList.add("spin");document.getElementById("rouletteResult").textContent="룰렛이 돌아가는 중...";setTimeout(()=>{let g=G[Math.floor(Math.random()*G.length)];w.classList.remove("spin");document.getElementById("rouletteResult").textContent="🎯 "+g.name},1400)};
document.getElementById("homeSearch").onsubmit=e=>{e.preventDefault();let q=document.getElementById("q").value.trim();location.href="category.html"+(q?"?q="+encodeURIComponent(q):"")};
})();
